"use client";

import { useLanguage } from "@/app/context/LanguageContext";
import Button from "@/components/ui/Button";
import { createDailyExpanse } from "@/services/dailyexpanse";
import jsPDF from "jspdf";
import React, { useState } from "react";
import toast from "react-hot-toast";
import { FiDownload } from "react-icons/fi";

export default function Page() {
  const { dictionary } = useLanguage();

  const [dailyExpanse, setDailyExpanse] = useState("");
  const [loading, setLoading] = useState(false);

  // ==========================
  // Download PDF
  // ==========================
  const handleDownloadPdf = () => {
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const marginX = 14;
    let y = 28;

    // Header
    doc.setFillColor(172, 200, 34);
    doc.rect(0, 0, pageWidth, 18, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");

    doc.text("Today's Expense", marginX, 11);

    doc.setTextColor(0, 0, 0);

    // Generated time
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    doc.text(`Generated: ${new Date().toLocaleString()}`, marginX, y);

    // Expense
    y += 15;

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");

    doc.text("Today's Expense:", marginX, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const expenseText = dailyExpanse.trim() ? dailyExpanse : "No expense added";

    const wrappedText = doc.splitTextToSize(
      expenseText,
      pageWidth - marginX * 2,
    );

    doc.text(wrappedText, marginX, y);

    // Footer
    const totalPages = doc.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);

      doc.setDrawColor(220);

      doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);

      doc.setFontSize(9);
      doc.setTextColor(120);

      doc.text("Generated by SOL Checklist System", 14, pageHeight - 8);

      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 8, {
        align: "right",
      });
    }

    doc.save("today-expense.pdf");
  };

  // ==========================
  // Save Expense
  // ==========================
  async function handleSaveExpense() {
    if (!dailyExpanse.trim()) {
      toast.error("Please enter today's expense.");
      return;
    }

    try {
      setLoading(true);

      await createDailyExpanse({
        DailyExpanse: dailyExpanse.trim(),
      });

      toast.success("Today's expense saved successfully.");

      setDailyExpanse("");
    } catch (error: any) {
      toast.error(
        error?.response?.data?.message ?? "Failed to save today's expense.",
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      {/* Top Action */}
      <div className="mb-6 flex justify-center sm:justify-end">
        <button
          onClick={handleDownloadPdf}
          className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#ACC822] px-5 py-3 text-sm font-semibold text-white shadow transition-all duration-300 hover:-translate-y-0.5 hover:bg-[#96B51D] hover:shadow-lg sm:w-auto"
        >
          <FiDownload size={18} />
          <span>Download PDF</span>
        </button>
      </div>

      {/* Expense Card */}
      <div className="mt-8 grid grid-cols-1 gap-6">
        <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition-all duration-300 hover:shadow-md sm:rounded-3xl sm:p-6 lg:p-8">
          {/* Header */}
          <div className="mb-5 flex items-start gap-3 sm:items-center sm:gap-4">
            <div className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-2xl bg-blue-100 text-xl sm:h-12 sm:w-12 sm:text-2xl lg:h-14 lg:w-14">
              💰
            </div>

            <div className="min-w-0">
              <h3 className="text-base font-bold text-slate-800 sm:text-lg lg:text-xl">
                {dictionary.expense.todaysExpense}
              </h3>

              <p className="mt-1 text-xs leading-5 text-slate-500 sm:text-sm">
                {dictionary.expense.expenseDescription}
              </p>
            </div>
          </div>

          {/* Textarea */}
          <textarea
            value={dailyExpanse}
            onChange={(e) => setDailyExpanse(e.target.value)}
            rows={6}
            placeholder={dictionary.expense.expensePlaceholder}
            className="min-h-[160px] w-full resize-y rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700 outline-none transition-all duration-300 placeholder:text-slate-400 focus:border-[#ACC822] focus:bg-white focus:ring-4 focus:ring-[#ACC822]/20 sm:p-4 sm:text-base"
          />

          {/* Save Expense Button */}
          <div className="mt-6 flex justify-end">
            <Button
              onClick={handleSaveExpense}
              disabled={loading}
              className="flex w-full items-center justify-center rounded-2xl bg-[#ACC822] px-6 py-3 text-sm font-semibold text-white shadow-lg transition-all duration-300 hover:-translate-y-0.5 hover:bg-[#96B51D] hover:shadow-xl disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto sm:px-8 sm:py-4 sm:text-base"
            >
              {loading ? (
                <>
                  <svg
                    className="mr-2 h-5 w-5 animate-spin"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    />

                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8v4a4 4 0 014-4H4z"
                    />
                  </svg>
                  Saving...
                </>
              ) : (
                "Save Expense"
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
