import jsPDF from "jspdf";

export function downloadHistoryPdf(item: any, type: string) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const marginX = 14;
  let y = 28;

  // ==========================================
  // HEADER
  // ==========================================
  doc.setFillColor(172, 200, 34);
  doc.rect(0, 0, pageWidth, 18, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  const title =
    type === "checklist"
      ? "Checklist History"
      : type === "appointment"
        ? "Appointment History"
        : "Daily Expense History";

  doc.text(title, marginX, 11);

  // Reset text
  doc.setTextColor(0, 0, 0);

  // ==========================================
  // USER INFORMATION
  // ==========================================
  doc.setFontSize(11);

  // User
  doc.setFont("helvetica", "bold");
  doc.text("User:", marginX, y);

  doc.setFont("helvetica", "normal");
  doc.text(item.user?.name || "Unknown User", marginX + 25, y);

  y += 7;

  // Email
  doc.setFont("helvetica", "bold");
  doc.text("Email:", marginX, y);

  doc.setFont("helvetica", "normal");
  doc.text(item.user?.email || "No email", marginX + 25, y);

  y += 7;

  // Date
  doc.setFont("helvetica", "bold");
  doc.text("Date:", marginX, y);

  doc.setFont("helvetica", "normal");
  doc.text(
    item.date ? new Date(item.date).toLocaleDateString() : "No date",
    marginX + 25,
    y,
  );

  y += 15;

  // ==========================================
  // CHECKLIST
  // ==========================================
  if (type === "checklist") {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");

    doc.text("Checklist Items", marginX, y);

    y += 9;

    doc.setFontSize(10);

    const answers = item.content?.answers || [];

    if (answers.length === 0) {
      doc.setFont("helvetica", "normal");
      doc.text("No checklist items available.", marginX, y);
    }

    answers.forEach((answer: any, index: number) => {
      const question = `${index + 1}. ${answer.question}`;

      const wrappedQuestion = doc.splitTextToSize(question, pageWidth - 55);

      doc.setFont("helvetica", "normal");

      doc.text(wrappedQuestion, marginX, y);

      doc.setFont("helvetica", "bold");

      doc.text(answer.answer || "-", pageWidth - 35, y);

      y += wrappedQuestion.length * 5 + 6;

      // New page if necessary
      if (y > pageHeight - 25) {
        doc.addPage();
        y = 25;
      }
    });
  }

  // ==========================================
  // APPOINTMENT
  // ==========================================
  if (type === "appointment") {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");

    doc.text("Appointment", marginX, y);

    y += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const appointmentText =
      item.content?.appointment || "No appointment details available.";

    const wrappedText = doc.splitTextToSize(
      appointmentText,
      pageWidth - marginX * 2,
    );

    doc.text(wrappedText, marginX, y);

    y += wrappedText.length * 6;
  }

  // ==========================================
  // DAILY EXPENSE
  // ==========================================
  if (type === "expense") {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");

    doc.text("Daily Expense", marginX, y);

    y += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const expenseText =
      item.content?.DailyExpanse || "No expense details available.";

    const wrappedText = doc.splitTextToSize(
      expenseText,
      pageWidth - marginX * 2,
    );

    doc.text(wrappedText, marginX, y);

    y += wrappedText.length * 6;
  }

  // ==========================================
  // FOOTER
  // ==========================================
  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    doc.setDrawColor(220);

    doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);

    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text("Generated by SOL Checklist System", 14, pageHeight - 8);

    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 8, {
      align: "right",
    });
  }

  // ==========================================
  // FILE NAME
  // ==========================================
  const userName =
    item.user?.name?.replace(/\s+/g, "-").toLowerCase() || "user";

  const fileName =
    type === "checklist"
      ? `${userName}-checklist-history.pdf`
      : type === "appointment"
        ? `${userName}-appointment-history.pdf`
        : `${userName}-daily-expense-history.pdf`;

  doc.save(fileName);
}
